INSERT INTO widgets (name, component_path, default_props) VALUES 
('ClockWidget', 'components/widgets/ClockWidget.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TopProjects1x1', 'components/widgets/TopProjects1x1.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TopOperativeSystems1x1', 'components/widgets/TopOperativeSystems1x1.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TopLanguages1x1', 'components/widgets/TopLanguages1x1.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TopMachines1x1', 'components/widgets/TopMachines1x1.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('MostActiveWeekday', 'components/widgets/MostActiveWeekday.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TotalTime', 'components/widgets/TotalTime.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}'),
('TodaysActivity', 'components/widgets/TodaysActivity.vue', '{"hideSettings":{"default":false},"widgetIndex":{"default":0},"widgetName":{"default":"no name provided"},"skin":{"default":"outline"},"timeRange":{"default":"week"},"widgetDrawerMode":{"default":false}}');
